
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
import java.io.IOException;
public class UserList extends javax.swing.JFrame {

    /**
     * Creates new form UserList
     */
    public UserList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlUserInput = new javax.swing.JTextPane();
        bttnAdd = new javax.swing.JButton();
        userNameList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        pnlUserInput.setName("pnlUserInput"); // NOI18N
        jScrollPane1.setViewportView(pnlUserInput);

        bttnAdd.setText("Add");
        bttnAdd.setName("bttnAdd"); // NOI18N
        bttnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnAddMouseClicked(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userNameList.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnAdd)
                .addGap(75, 75, 75)
                .addComponent(userNameList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bttnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        bttnAdd.getAccessibleContext().setAccessibleName("addName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bttnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnAddMouseClicked

    }//GEN-LAST:event_bttnAddMouseClicked

   
    
 
    private void addName(List nameList, BufferedWriter fullNameListBw) {

        String fullName = pnlUserInput.getText();
        nameList.add(fullName);
        pnlUserInput.setText("");
        
        try {
            fullNameListBw.write(fullName);
            fullNameListBw.newLine();

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void removeNameIndex(List nameList, BufferedWriter fullNameListBw) throws FileNotFoundException {
        Scanner mySc = new Scanner(System.in);

        System.out.println("Enter user index to remove");
        int nameIndex = mySc.nextInt();
        nameList.remove(nameIndex);
        System.out.println(nameIndex + " Was removed");
        PrintWriter pw = new PrintWriter("C:\\Users\\admin\\Desktop\\FullNameList.txt");
        pw.close();

        try {
            for (int i = 0; i < nameList.size(); i++) {

                String ass = (String) nameList.get(i);
                fullNameListBw.write(ass);
                fullNameListBw.newLine();

            }
        }  catch (Exception e) {
            System.out.println(e);
        }
    }

    private static void removeName(List nameList, BufferedWriter fullNameListBw) throws FileNotFoundException {
        Scanner mySc = new Scanner(System.in);

        System.out.println("Enter the full name of person to be removed");
        String userDead = mySc.nextLine();
        nameList.remove(userDead);
        System.out.println(userDead + " Was removed");

        PrintWriter pw = new PrintWriter("C:\\Users\\admin\\Desktop\\FullNameList.txt");
        pw.close();

        try {
            for (int i = 0; i < nameList.size(); i++) {

                String ass = (String) nameList.get(i);
                fullNameListBw.write(ass);
                fullNameListBw.newLine();

            }
        }  catch (Exception e) {
            System.out.println(e);
        }

    }
    
    
    
    public static void main(String args[]) throws IOException {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserList().setVisible(true);
            }
        });
        
        List<String> nameList = new ArrayList<String>();

        FileReader fullNameListFr = new FileReader("C:\\Users\\admin\\Desktop\\FullNameList.txt");
        FileWriter fullNameListFw = new FileWriter("C:\\Users\\admin\\Desktop\\FullNameList.txt", true);
        BufferedReader fullNameListBr = new BufferedReader(fullNameListFr);
        BufferedWriter fullNameListBw = new BufferedWriter(fullNameListFw);
        String st;
        while ((st = fullNameListBr.readLine()) != null) {
            nameList.add(st);
        }

        while (true) {
            System.out.println("");
            for (int j = 0; j < nameList.size(); j++) {
                 
            }
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAdd;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane pnlUserInput;
    private javax.swing.JScrollPane userNameList;
    // End of variables declaration//GEN-END:variables
}
